# Generated by Django 4.2.14 on 2024-07-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_reviewmodel_ratting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='ratting',
            field=models.IntegerField(choices=[('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('2', '⭐⭐'), ('1', '⭐'), ('5', '⭐⭐⭐⭐⭐')]),
        ),
    ]
