# Generated by Django 4.2.14 on 2024-07-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_reviewmodel_ratting'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='average_rating',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='ratting',
            field=models.IntegerField(choices=[('5', '⭐⭐⭐⭐⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('1', '⭐')]),
        ),
    ]
