# Generated by Django 4.2.14 on 2024-07-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_service_average_rating_alter_reviewmodel_ratting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='average_rating',
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='ratting',
            field=models.IntegerField(choices=[('3', '⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('2', '⭐⭐'), ('1', '⭐')]),
        ),
    ]
