# Generated by Django 4.2.14 on 2024-08-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_reviewmodel_ratting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='ratting',
            field=models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (5, '⭐⭐⭐⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐')]),
        ),
    ]
