# Generated by Django 5.1.1 on 2024-09-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_alter_reviewmodel_ratting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='ratting',
            field=models.IntegerField(choices=[(3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (2, '⭐⭐'), (5, '⭐⭐⭐⭐⭐'), (1, '⭐')]),
        ),
    ]
