# Generated by Django 5.1.1 on 2024-10-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_alter_reviewmodel_ratting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='ratting',
            field=models.IntegerField(choices=[(1, '⭐'), (4, '⭐⭐⭐⭐'), (2, '⭐⭐'), (5, '⭐⭐⭐⭐⭐'), (3, '⭐⭐⭐')]),
        ),
    ]
