# Generated by Django 4.2.14 on 2024-07-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_alter_reviewmodel_ratting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='ratting',
            field=models.IntegerField(choices=[(2, '⭐⭐'), (5, '⭐⭐⭐⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (1, '⭐')]),
        ),
    ]
