# Generated by Django 5.1.1 on 2024-10-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_alter_reviewmodel_ratting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='ratting',
            field=models.IntegerField(choices=[(5, '⭐⭐⭐⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (2, '⭐⭐'), (1, '⭐')]),
        ),
    ]
