# Generated by Django 5.1.1 on 2024-10-28 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_alter_customer_dp'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerorderinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=18)),
                ('address', models.CharField(max_length=200)),
                ('payment_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chooce', models.CharField(choices=[('Monday 5PM to 8PM', 'Monday 5PM to 8PM'), ('sunday 2PM to 5PM', 'sunday 2PM to 5PM'), ('saturday 9AM to 2PM', 'saturday 9AM to 2PM')], max_length=50)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('main_payment', models.IntegerField(blank=True, null=True)),
                ('service_status', models.CharField(blank=True, choices=[('pending', 'pending'), ('cancel', 'cancel'), ('Done', 'Done')], default='pending', max_length=50, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
        ),
    ]
