# Generated by Django 5.1.1 on 2024-10-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceslot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceslot',
            name='chooce',
            field=models.CharField(choices=[('sunday 2PM to 5PM', 'sunday 2PM to 5PM'), ('saturday 9AM to 2PM', 'saturday 9AM to 2PM'), ('Monday 5PM to 8PM', 'Monday 5PM to 8PM')], max_length=50),
        ),
    ]
