# Generated by Django 4.2.14 on 2024-08-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceslot', '0002_alter_serviceslot_chooce_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceslot',
            name='service_status',
            field=models.CharField(blank=True, choices=[('cancel', 'cancel'), ('pending', 'pending'), ('Done', 'Done')], default='pending', max_length=50, null=True),
        ),
    ]
