# Generated by Django 5.1.1 on 2024-09-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceslot', '0007_alter_serviceslot_chooce_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceslot',
            name='service_status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('cancel', 'cancel'), ('Done', 'Done')], default='pending', max_length=50, null=True),
        ),
    ]
