# Generated by Django 5.1.1 on 2024-10-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceslot', '0010_alter_serviceslot_chooce_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerorderinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=18)),
                ('address', models.CharField(max_length=200)),
                ('payment_amount', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='serviceslot',
            name='main_payment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceslot',
            name='chooce',
            field=models.CharField(choices=[('sunday 2PM to 5PM', 'sunday 2PM to 5PM'), ('Monday 5PM to 8PM', 'Monday 5PM to 8PM'), ('saturday 9AM to 2PM', 'saturday 9AM to 2PM')], max_length=50),
        ),
    ]
