# Generated by Django 5.1.1 on 2024-10-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceslot', '0014_alter_serviceslot_chooce_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceslot',
            name='chooce',
            field=models.CharField(choices=[('Monday 5PM to 8PM', 'Monday 5PM to 8PM'), ('saturday 9AM to 2PM', 'saturday 9AM to 2PM'), ('sunday 2PM to 5PM', 'sunday 2PM to 5PM')], max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceslot',
            name='service_status',
            field=models.CharField(blank=True, choices=[('cancel', 'cancel'), ('Done', 'Done'), ('paid', 'paid'), ('Cash on delivery', 'cash on delivery'), ('pending', 'pending')], default='pending', max_length=50, null=True),
        ),
    ]
